[BE] 엑세스 토큰 재발급 오류 해결
String 타입으로 전달되는 id 값을 Long 타입으로 추출하려고 하면서 에러 발생 했었음

org.springframework.web.method.annotation.MethodArgumentTypeMismatchException: Failed to convert value of type 'java.lang.String' to required type 'java.lang.Long'; nested exception is java.lang.NumberFormatException: For input string: \"null\"\n\tat